version: '2'
services:
    plex:
        build: ./plex
        privileged: true
        network_mode: host
        volumes:
          - 'config:/data'
        ports:
          - "32400:32400/tcp"
          - "1900:1900/udp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
          - "32469:32469/tcp"
    # reader:
    #   image: hectorqin/reader:openj9-latest #docker镜像，arm64架构或小内存机器优先使用此镜像.启用需删除上一行
    #   container_name: reader
    #   restart: always
    #   ports:
    #     - 4396:8080
    #   volumes:
    #     - 'storage:/storage'
    #   environment:
    #     - SPRING_PROFILES_ACTIVE=prod
    #     - READER_APP_USERBOOKLIMIT=200 #用户书籍上限,默认200
    #     - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容 V2.0
    # navidrome:
    #   image: deluan/navidrome:latest
    #   container_name: navidrome
    #   ports:
    #     - "4533:4533"
    #   environment:
    #     ND_SCANSCHEDULE: 1h
    #     ND_LOGLEVEL: info  
    #     ND_BASEURL: ""
    #   volumes:
    #     - "config:/data"
    #     - "storage:/music:ro"
    alist:
      image: 'xhofe/alist:latest'
      container_name: alist
      ports:
        - '8081:5244'
      environment:
        - PUID=0
        - PGID=0
        - UMASK=022
      volumes:
        - "config:/opt/alist/data"
        - "storage:/mnt/data"
    freshrss:
      image: lscr.io/linuxserver/freshrss:latest
      container_name: freshrss
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Toronto
      volumes:
        - config:/config
      ports:
        - 8082:80

volumes:
  config:
  storage:
